### ISSUE TITLE
Plugin Causes Transformation Previews to fail with NPE

### ISSUE THREAD

**Issue by cdeptula** [mattcasters/pentaho-pdi-dataset#1]
When this plugin is installed, attempting to preview a transformation fails with the following NPE.  If you uninstall this plugin, preview works.

java.lang.NullPointerException
    at org.pentaho.di.trans.step.BaseStep.openRemoteOutputStepSocketsOnce(BaseStep.java:1942)
    at org.pentaho.di.trans.step.BaseStep.initBeforeStart(BaseStep.java:3738)
    at org.pentaho.di.trans.Trans.startThreads(Trans.java:1195)
    at org.pentaho.di.ui.spoon.trans.TransGraph.startThreads(TransGraph.java:4040)
    at org.pentaho.di.ui.spoon.trans.TransGraph.debug(TransGraph.java:3783)
    at org.pentaho.di.ui.spoon.delegates.SpoonTransformationDelegate.executeTransformation(SpoonTransformationDelegate.java:878)
    at org.pentaho.di.ui.spoon.Spoon$31$1.run(Spoon.java:8548)
    at org.eclipse.swt.widgets.RunnableLock.run(Unknown Source)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Unknown Source)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
    at org.pentaho.di.ui.spoon.Spoon.readAndDispatch(Spoon.java:1316)
    at org.pentaho.di.ui.spoon.Spoon.waitForDispose(Spoon.java:7979)
    at org.pentaho.di.ui.spoon.Spoon.start(Spoon.java:9310)
    at org.pentaho.di.ui.spoon.Spoon.main(Spoon.java:654)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.pentaho.commons.launcher.Launcher.main(Launcher.java:92)

**Comment by diethardsteiner** [comment]
+1. I can see this issue as well.

**Comment by sramazzina** [comment]
+1. Same issue here

**Comment by mattcasters** [comment]
Fixed
