### ISSUE TITLE
Execute Unit Tests throws exception when running with pan.sh

### ISSUE THREAD

**Issue by peterborkuti** [mattcasters/pentaho-pdi-dataset#51]
Dear @mattcasters ,

I would like to run unit tests with pan.sh to check them at once and make a report about the unit test failures.

When I am using Execute Unit Tests step from spoon GUI, it works well.

When I try to running it from the command line, it throws the exception:
```
2019/03/03 09:59:13 - Pan - Start of run.
2019/03/03 09:59:13 - executeunittests - Dispatching started for transformation [executeunittests]
log4j:ERROR No output stream or file set for the appender named [pdi-execution-appender].
2019/03/03 09:59:31 - Execute Unit Tests.0 - ERROR (version 8.3.0.0-SNAPSHOT, build 8.3.0.0-SNAPSHOT from 2019-02-28 08.37.11 by peter) : Unable to load information from the metastore
2019/03/03 09:59:31 - Execute Unit Tests.0 - ERROR (version 8.3.0.0-SNAPSHOT, build 8.3.0.0-SNAPSHOT from 2019-02-28 08.37.11 by peter) : java.lang.NullPointerException
2019/03/03 09:59:31 - Execute Unit Tests.0 - 	at org.pentaho.metastore.persist.MetaStoreFactory.getElements(MetaStoreFactory.java:779)
2019/03/03 09:59:31 - Execute Unit Tests.0 - 	at org.pentaho.di.dataset.util.FactoriesHierarchy.<init>(FactoriesHierarchy.java:48)
2019/03/03 09:59:31 - Execute Unit Tests.0 - 	at org.pentaho.di.dataset.steps.exectests.ExecuteTests.init(ExecuteTests.java:65)
2019/03/03 09:59:31 - Execute Unit Tests.0 - 	at org.pentaho.di.trans.step.StepInitThread.run(StepInitThread.java:69)
2019/03/03 09:59:31 - Execute Unit Tests.0 - 	at java.lang.Thread.run(Thread.java:748)
2019/03/03 09:59:31 - Execute Unit Tests.0 - ERROR (version 8.3.0.0-SNAPSHOT, build 8.3.0.0-SNAPSHOT from 2019-02-28 08.37.11 by peter) : Error initializing step [Execute Unit Tests]
2019/03/03 09:59:31 - executeunittests - ERROR (version 8.3.0.0-SNAPSHOT, build 8.3.0.0-SNAPSHOT from 2019-02-28 08.37.11 by peter) : Step [Execute Unit Tests.0] failed to initialize!
Unable to prepare and initialize this transformation
```

I debugged it and the cause of the null pointer exception is that in ExecuteTests.init line 65, metaStore is null:
```
data.hierarchy = new FactoriesHierarchy( metaStore, getTransMeta().getDatabases() );
```
Unfortunately, I do not know why. When using the Spoon GUI, it is not null.

I used the command line for running the transformation with the Execute Unit Tests step:
```
./pan.sh -file=/home/peter/work/kettle/executeunittests.ktr
``

Thank you in advance

Péter Borkut

**Comment by mattcasters** [comment]
Unfortunately I tried to have Pentaho fix this issue for a while now without result.
Pan/Kitchen are unfortunately fundamentally broken.
That is why I created a better shell script...

Try maitre.sh to be found in https://github.com/mattcasters/kettle-needful-things
Or download a remix version from http://www.kettle.be

**Comment by peterborkuti** [comment]
Thank you @mattcasters ,
I debugged it a bit more and I guessed, that the root cause of this issue is not in your plugin, but somewhere in pentaho.

Thank you for the links and you great work, I am checking.

**Comment by peterborkuti** [comment]
Dear @mattcasters ,

I used kettle-neo4j-remix-8.2.0.3-519-REMIX.zip.
It sees the metastore and found all the unit test transformations, however, in DataSetHelper getInstance method SpoonFactory.getInstance() returns with null.

```
2019/03/27 14:00:22 - run-ut - Dispatching started for transformation [run-ut]
log4j:ERROR No output stream or file set for the appender named [pdi-execution-appender].
java.lang.NullPointerException
	at org.pentaho.di.dataset.spoon.DataSetHelper.getInstance(DataSetHelper.java:107)
	at org.pentaho.di.dataset.spoon.DataSetHelper.selectUnitTest(DataSetHelper.java:1078)
	at org.pentaho.di.dataset.steps.exectests.ExecuteTests.loadTestTransformation(ExecuteTests.java:301)
	at org.pentaho.di.dataset.steps.exectests.ExecuteTests.processRow(ExecuteTests.java:160)
	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
	at java.lang.Thread.run(Thread.java:748)
2019/03/27 14:13:46 - Execute Unit Tests.0 - ERROR (version 8.2.0.3-519, build 8.2.0.3-519 from 2019-02-09 02.49.53 by kettle) : Unexpected error
2019/03/27 14:13:46 - Execute Unit Tests.0 - ERROR (version 8.2.0.3-519, build 8.2.0.3-519 from 2019-02-09 02.49.53 by kettle) : java.lang.NullPointerException
2019/03/27 14:13:46 - Execute Unit Tests.0 - 	at org.pentaho.di.dataset.spoon.DataSetHelper.getInstance(DataSetHelper.java:107)
2019/03/27 14:13:46 - Execute Unit Tests.0 - 	at org.pentaho.di.dataset.spoon.DataSetHelper.selectUnitTest(DataSetHelper.java:1078)
2019/03/27 14:13:46 - Execute Unit Tests.0 - 	at org.pentaho.di.dataset.steps.exectests.ExecuteTests.loadTestTransformation(ExecuteTests.java:301)
2019/03/27 14:13:46 - Execute Unit Tests.0 - 	at org.pentaho.di.dataset.steps.exectests.ExecuteTests.processRow(ExecuteTests.java:160)
2019/03/27 14:13:46 - Execute Unit Tests.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2019/03/27 14:13:46 - Execute Unit Tests.0 - 	at java.lang.Thread.run(Thread.java:748)
2019/03/27 14:13:46 - Execute Unit Tests.0 - Finished processing (I=0, O=0, R=0, W=0, U=0, E=1)
2019/03/27 14:13:46 - run-ut - Transformation duration : 804.32 seconds [ 13' 24.320" ]
2019/03/27 14:13:46 - run-ut - Transformation detected one or more steps with errors.
2019/03/27 14:13:46 - run-ut - Transformation is killing the other steps!
```

I used the command:
./maitre.sh -f /home/peter/kettle-home-2/run-ut.ktr

Where run-ut.ktr is a transformation with only an Execute Unit Tests step.

I also tried creating the Default environment with spoon and using that with -e from command line, but no luck.

Do you have any clue?

Thank you in advance
Péter

**Comment by peterborkuti** [comment]
Dear @mattcasters 

I checked the null value 
```
public static DataSetHelper getInstance() {
    if ( instance == null ) {
      instance = new DataSetHelper();
      Spoon spoon = ( (Spoon) SpoonFactory.getInstance() );
      if (spoon != null) {
        spoon.addSpoonMenuController(instance);
      }
    }
    return instance;
  }
```

And now it works. Thank you.

**Comment by mattcasters** [comment]
Hi Peter, is this a bug/change to pentaho-pdi-dataset?

**Comment by peterborkuti** [comment]
Hi Matt,

Yes, I assume. I am sending you a pull request.

Péter

**Comment by mattcasters** [comment]
Thanks a lot Peter, I really appreciate it.

**Comment by mattcasters** [comment]
I'm happy to make you a collaborator.

**Comment by peterborkuti** [comment]
I am proud, that I could add a bit to your great project.
Thank you for your helpful support.
I am closing this because the root cause is not in your plugin and you made a workaround.
